namespace :db do
  desc "Create sample data"
  task :populate => :environment do
    Rake::Task['db:reset'].invoke
    
    s = Subject.create!(:subject_name => "Tang Soo Do")
    t = s.topics.create!(:topic_name => "10 Key Concepts")
    t.terms.create!(:question => "1. Yong Gi           ", :answer => "1. Courage             ")
    t.terms.create!(:question => "2. In Neh            ", :answer => "2. Endurance           ")
    t.terms.create!(:question => "3. Chung Shin Tong Il", :answer => "3. Concentration       ")
    t.terms.create!(:question => "4. Chung Jik         ", :answer => "4. Honesty             ")
    t.terms.create!(:question => "5. Kyum Son          ", :answer => "5. Humility            ")
    t.terms.create!(:question => "6. Him Cho Chung     ", :answer => "6. Control of Power    ")
    t.terms.create!(:question => "7. Shin Chook        ", :answer => "7. Tension & Relaxation")
    t.terms.create!(:question => "8. Wan Gup           ", :answer => "8. Speed Control       ")
    t.terms.create!(:question => "9. Jung Uei          ", :answer => "9. Justice             ")
    t.terms.create!(:question => "10. Uei Rhee         ", :answer => "10.Best Friendship     ")

    t = s.topics.create!(:topic_name => "Articles of Faith")
    t.terms.create!(:question => "1. ", :answer => "Be loyal to one's country            ")
    t.terms.create!(:question => "2. ", :answer => "Be obedient to one's parents & elders")
    t.terms.create!(:question => "3. ", :answer => "Be loving to one's husband or wife   ")
    t.terms.create!(:question => "4. ", :answer => "Be cooperative to your brothers      ")
    t.terms.create!(:question => "5. ", :answer => "Be respectful to elders              ")
    t.terms.create!(:question => "6. ", :answer => "Be faithful to your teacher          ")
    t.terms.create!(:question => "7. ", :answer => "Be faithful to friends               ")
    t.terms.create!(:question => "8. ", :answer => "Kill only in justice and with honor  ")
    t.terms.create!(:question => "9. ", :answer => "Never retreat in battle              ")
    t.terms.create!(:question => "10.", :answer => "Always finish what you start         ")

    s = Subject.create!(:subject_name => "Cisco Network Engineer")
    t = s.topics.create!(:topic_name => "Chapter 2")
        
    t.terms.create!(:question => "RFC 1700 defines what well-known ports for DNS?", :answer => "TCP/UDP port 53")
    t.terms.create!(:question => "What supplies DNS security?", :answer => "None of the above...what?????")
    t.terms.create!(:question => "What IOS command will stop a Cisco router from querying a DNS server when an invalid IOS command is entered on the EXEC or PRIV prompt?", :answer => "no ip domain-lookup")
    t.terms.create!(:question => "What does the following Global IOS configuration line accomplish? ip host SimonisaCCIE 131.108.1.1 131.108.1.2", :answer => "Defines a local host name, SimonisaCCIE, mapped to IP addresses 131.108.1.1 and 131.108.1.2")
    t.terms.create!(:question => "TFTP uses what predefined UDP port number?", :answer => "TFTP uses UDP port number 69.")
    t.terms.create!(:question => "What IOS command will copy an IOS image from the current system flash to a TFTP server?", :answer => "copy flash tftp")
    t.terms.create!(:question => "Suppose a client calls and advises you that an FTP data transaction is not allowing him to view the host's directory structure. What are the most likely causes of the problem?", :answer => "The FTP data port is used to view the directory and could be blocked because of an access list or a fault with the client's software when establishing the FTP 20 connection.")
    t.terms.create!(:question => "FTP runs over what Layer 4 protocol?", :answer => "The FTP application is a connection-orientated protocol and is part of the TCP/IP protocol suite. FTP ensures data is delivered by running data with a TCP overhead.")
    t.terms.create!(:question => "HTTPS traffic uses what TCP port number?", :answer => "443")
    t.terms.create!(:question => "SNMP is restricted on Cisco routers by what IOS command?", :answer => "snmp-server community string")
    t.terms.create!(:question => "TFTP protocol uses which ports", :answer => "Can use UDP/TCP and port 69")
    t.terms.create!(:question => "What is the HELO SMTP command used for?", :answer => "To identify SMTP clients")
    t.terms.create!(:question => "POP3 clients can do what?", :answer => "Send mail")
    t.terms.create!(:question => "NTP uses what well-known TCP port?", :answer => "NTP uses UDP or TCP, and the port number is 123")
    t.terms.create!(:question => "Secure Shell (SSH) is used to do what?", :answer => "SSH is used to protect TCP/IP hosts.")
    t.terms.create!(:question => "Which protocols can be authenticated?", :answer => "Telnet, HTTP, HTTPS, FTP")
    t.terms.create!(:question => "What is the community string value when the following IOS commands are entered in global configuration mode?  snmp-server community publiC RO   snmp-server enable traps config   snmp-server host 131.108.255.254 isdn", :answer => "The community string is defined by the command snmp-server community community string, which, in this case, is set to publiC")
    t.terms.create!(:question => "What UDP port number will SNMP traps be sent from?", :answer => "162")
    t.terms.create!(:question => "What TCP port number will an SNMP inform acknowledgment packet be sent to?", :answer => "SNMP inform acknowledgments are sent over UDP (not TCP) port number 161.")
    t.terms.create!(:question => "what IOS command is required to restrict SNMP managers from the source network 131.108.1.0/30?", :answer => "snmp-server community SimonisCool ro 4   access-list 4 permit 131.108.1.0 0.0.0.252")


    s = Subject.create!(:subject_name => "U.S. Information")
    t = s.topics.create!(:topic_name => "State Capitals")
    
    t.terms.create!(:question => "Montgomery", :answer => "Alabama")  
    t.terms.create!(:question => "Helena", :answer => "Montana")
    t.terms.create!(:question => "Juneau", :answer => "Alaska")   
    t.terms.create!(:question => "Lincoln", :answer => "Nebraska")
    t.terms.create!(:question => "Phoenix", :answer => "Arizona")  
    t.terms.create!(:question => "Carson City", :answer => "Nevada")
    t.terms.create!(:question => "Little Rock", :answer => "Arkansas") 
    t.terms.create!(:question => "Concord", :answer => "New Hampshire")
    t.terms.create!(:question => "Sacramento", :answer => "California")  
    t.terms.create!(:question => "Trenton", :answer => "New Jersey")
    t.terms.create!(:question => "Denver", :answer => "Colorado") 
    t.terms.create!(:question => "Santa Fe", :answer => "New Mexico")
    t.terms.create!(:question => "Hartford", :answer => "Connecticut") 
    t.terms.create!(:question => "Albany", :answer => "New York")
    t.terms.create!(:question => "Dover", :answer => "Delaware") 
    t.terms.create!(:question => "Raleigh", :answer => "North Carolina")
    t.terms.create!(:question => "Tallahassee", :answer => "Florida")  
    t.terms.create!(:question => "Bismarck", :answer => "North Dakota")
    t.terms.create!(:question => "Atlanta", :answer => "Georgia")  
    t.terms.create!(:question => "Columbus", :answer => "Ohio")
    t.terms.create!(:question => "Honolulu", :answer => "Hawaii")   
    t.terms.create!(:question => "Oklahoma City", :answer => "Oklahoma")
    t.terms.create!(:question => "Boise", :answer => "Idaho") 
    t.terms.create!(:question => "Salem", :answer => "Oregon")
    t.terms.create!(:question => "Springfield", :answer => "Illinois") 
    t.terms.create!(:question => "Harrisburg", :answer => "Pennsylvania")
    t.terms.create!(:question => "Indianapolis", :answer => "Indiana")  
    t.terms.create!(:question => "Providence", :answer => "Rhode Island")
    t.terms.create!(:question => "Des Moines", :answer => "Iowa")  
    t.terms.create!(:question => "Columbia", :answer => "South Carolina")
    t.terms.create!(:question => "Topeka", :answer => "Kansas")   
    t.terms.create!(:question => "Pierre", :answer => "South Dakota")
    t.terms.create!(:question => "Frankfort", :answer => "Kentucky") 
    t.terms.create!(:question => "Nashville", :answer => "Tennessee")
    t.terms.create!(:question => "Baton Rouge", :answer => "Louisiana")   
    t.terms.create!(:question => "Austin", :answer => "Texas")
    t.terms.create!(:question => "Augusta", :answer => "Maine") 
    t.terms.create!(:question => "Salt Lake City", :answer => "Utah")
    t.terms.create!(:question => "Annapolis", :answer => "Maryland") 
    t.terms.create!(:question => "Montpelier", :answer => "Vermont")
    t.terms.create!(:question => "Boston", :answer => "Massachusetts")  
    t.terms.create!(:question => "Richmond", :answer => "Virginia")
    t.terms.create!(:question => "Lansing", :answer => "Michigan") 
    t.terms.create!(:question => "Olympia", :answer => "Washington")
    t.terms.create!(:question => "Saint Paul", :answer => "Minnesota")   
    t.terms.create!(:question => "Charleston", :answer => "West Virginia")
    t.terms.create!(:question => "Jackson", :answer => "Mississippi") 
    t.terms.create!(:question => "Madison", :answer => "Wisconsin")
    t.terms.create!(:question => "Jefferson City", :answer => "Missouri") 
    t.terms.create!(:question => "Cheyenne", :answer => "Wyoming")

    t = s.topics.create!(:topic_name => "Tennessee Questions")

    t.terms.create!(:question => "This TN President built the Hermitage", :answer => "Andrew Jackson")
    t.terms.create!(:question => "This Tennessean was the 11th US President", :answer => "James Polk")
    t.terms.create!(:question => "This Tennessean President was the first president to ever be impeached", :answer => "Andrew Johnson")
    t.terms.create!(:question => "The capital of Tennessee", :answer => "Nashville")
    t.terms.create!(:question => "What is the Tennessee state nickname?", :answer => "The Volunteer State")
    t.terms.create!(:question => "What is the Tennessee state bird?", :answer => "Mockingbird")
    t.terms.create!(:question => "What is the Tennessee state insect?", :answer => "Firefly")
    t.terms.create!(:question => "What is the largest city in Tennessee?", :answer => "Memphis")
    t.terms.create!(:question => "The 1982 World's Fair was held in which Tennessee city?", :answer => "Knoxville")
    t.terms.create!(:question => "What does the name \"Tennessee\" mean?", :answer => "The meeting place")
    t.terms.create!(:question => "What award winning novelist got his \"roots\" while living on a 127 acre farm in Henning as a young boy?", :answer => "Alex Haley")
    t.terms.create!(:question => "What American explorer was said to have been so depressed that he took his own life in Hohenwald, TN in 1809?", :answer => "Meriwether Lewis")
    t.terms.create!(:question => "The TN state flag is made up of what three colors?", :answer => "Red, White & Blue")
    t.terms.create!(:question => "What runs through the state of TN twice?", :answer => "Tennessee River")
    t.terms.create!(:question => "What do the three stars on the TN state flag represent?", :answer => "3 Grand Divisions")
    t.terms.create!(:question => "Chattanooga is home of what chocolate, graham cracker, marshmallow snack cake?", :answer => "Moonpie snacks")
    t.terms.create!(:question => "What college in Greeneville founded in 1794 is the oldest in the state of Tennessee and the 28th oldest in the nation?", :answer => "Tusculum College")
    t.terms.create!(:question => "What was the first newspaper to be published in Tennessee?", :answer => "Knoxville Gazette (1791)")
    t.terms.create!(:question => "What type of music was created along Beale Street in Memphis?", :answer => "Blues")
    t.terms.create!(:question => "What two time Pulitzer prize winning playwright had his first play produced in Memphis?", :answer => "Tennessee Williams")
    t.terms.create!(:question => "What famous breed of animal known for its distinctively smooth gait is bred largely in middle Tennessee?", :answer => "Walking Horse")
    t.terms.create!(:question => "What popular advertisement can be seen painted on the roofs of barns all throughout the state of Tennessee?", :answer => "See Rock City")
    t.terms.create!(:question => "What Nashville State park contains the largest red-cedar forest in the Eastern United States?", :answer => "Cedars of Lebanon")
    t.terms.create!(:question => "What Grammy winning singer/ songwriter/ actress was born in Locust Ridge near Sevierville?", :answer => "Dolly Parton")
    t.terms.create!(:question => "What national park in Tennessee is the largest park in the United States?", :answer => "Smoky Mountain")
    t.terms.create!(:question => "Tennessee's state capital Nashville, is also known by what nickname?", :answer => "Music City USA")
    t.terms.create!(:question => "Where is America's highest underground waterfall that is open to the public?", :answer => "Ruby Falls")
    t.terms.create!(:question => "Dayton was the location for what famous trial in 1925?", :answer => "Scopes-Monkey Trial")
    t.terms.create!(:question => "Where is the reputed \"Turtle Capital of the World\"?", :answer => "Reelfoot Lake")
    t.terms.create!(:question => "Tennessee is documented to have more than 3,800 of these.", :answer => "Caves")
    t.terms.create!(:question => "At 6,643 ft., what is the highest point in Tennessee and is the second highest point in the Eastern United States?", :answer => "Clingmans Dome")
    t.terms.create!(:question => "What underground lake in Sweetwater is the largest in the United States?", :answer => "Lost Sea")
    t.terms.create!(:question => "What Tennessee city is known as the \"Athens of the South\"?", :answer => "Nashville")
    t.terms.create!(:question => "Tennessee is second behind Alaska as the largest producer of what mineral?", :answer => "Zinc")
    t.terms.create!(:question => "Partly located in East, TN what is the largest Historical park in the United States?", :answer => "Cumberland Gap National Historical Park")
    t.terms.create!(:question => "In April of 1862, over 20,000 men died in this Civil War battle at Pittsburgh Landing, TN.", :answer => "Battle of Shiloh")
    t.terms.create!(:question => "Where can you find a 256 ft. waterfall in east-central Tennessee?", :answer => "Fall Creek Falls State Park")
    t.terms.create!(:question => "What is the largest State Park in Tennessee?", :answer => "Natchez Trace State Park")
    t.terms.create!(:question => "What 501 mile parkway extends from Nashville all the way to Mississippi?", :answer => "Natchez Trace Parkway")
    t.terms.create!(:question => "Started in 1956, what is the oldest festival held in Tennessee?", :answer => "Ramp Festival in Cosby, TN")
    t.terms.create!(:question => "Where was the first major Union victory fought in the Civil War?", :answer => "Fort Donelson (1862)")
    t.terms.create!(:question => "Where is the fourth largest cave in the U.S?", :answer => "Cumberland Caverns, McMinnville")
    t.terms.create!(:question => "What Carthage native served as U.S. Vice President from 1993-2001?", :answer => "Albert Gore Jr.")
    t.terms.create!(:question => "What World War I hero was born in Pall Mall in 1887?", :answer => "Alvin Cullum York (Sergeant York)")
    t.terms.create!(:question => "What secret weapon of mass destruction was first assembled in Oak Ridge in 1945?", :answer => "Atomic Bomb")
    t.terms.create!(:question => "What American Indian tribe was denied an appeal for government protection by President Andrew Jackson?", :answer => "Cherokee")
    t.terms.create!(:question => "What Amer. Politician and frontiersman from TN was killed at the Alamo?", :answer => "Davy Crockett")
    t.terms.create!(:question => "Who was the first Governor of Tennessee?", :answer => "John Sevier")
    t.terms.create!(:question => "What American civil rights leader and Nobel prize winner was assassinated on April 4, 1968 in Memphis?", :answer => "Martin Luther King Jr.")
    t.terms.create!(:question => "What citrus soft drink that was invented in Tennessee derived its name from moonshine?", :answer => "Mountain Dew")
    t.terms.create!(:question => "What military commander and Tennessee governor resigned his position and went to live with the Cherokee Indians?", :answer => "Sam Houston")

    t = s.topics.create!(:topic_name => "Citizenship Questions")
    
    t.terms.create!(:question => "What are the colors of our flag?", :answer => "Red, white, and blue")
    t.terms.create!(:question => "How many stars are there in our flag?", :answer => "Fifty  (50)")
    t.terms.create!(:question => "What colors are the stars on our flag?", :answer => "White")
    t.terms.create!(:question => "What do the stars on our flag mean?", :answer => "One for each state in the Union (United States)")
    t.terms.create!(:question => "How many stripes are there in the flag?", :answer => "Thirteen  (13)")
    t.terms.create!(:question => "What color are the stripes?", :answer => "Red and white")
    t.terms.create!(:question => "What do the stripes on the flag mean?", :answer => "They represent the original thirteen  (13) states")
    t.terms.create!(:question => "How many states are there in the Union  (United States)?", :answer => "Fifty (50)")
    t.terms.create!(:question => "What is the Fourth of July?", :answer => "Independence Day")
    t.terms.create!(:question => "What is the date of Independence Day?", :answer => "The Fourth of July")
    t.terms.create!(:question => "Independence from whom?", :answer => "England")
    t.terms.create!(:question => "What country did we fight during the Revolution War?", :answer => "England")
    t.terms.create!(:question => "Who was the first President of the United States?", :answer => "George Washington")
    t.terms.create!(:question => "Who is the President of the United States today?", :answer => "Barack Obama")
    t.terms.create!(:question => "Who is the Vice-President of the United States today?", :answer => "Joseph Biden")
    t.terms.create!(:question => "Who elects the President of the United States?", :answer => "Electoral College")
    t.terms.create!(:question => "Who became President of the United States if the President should die?", :answer => "Vice-President")
    t.terms.create!(:question => "For how long do we elect the President?", :answer => "Four  (4) years")
    t.terms.create!(:question => "What is the Constitution?", :answer => "The supreme law of the land")
    t.terms.create!(:question => "Can the Constitution be changed?", :answer => "Yes")
    t.terms.create!(:question => "What do we call a change to the  Constitution ?", :answer => "An amendment")
    t.terms.create!(:question => "How many changes or amendments are there to the Constitution?", :answer => "Twenty-seven (27)")
    t.terms.create!(:question => "How many branches are there in our government?", :answer => "Three (3)")
    t.terms.create!(:question => "What are the three branches of our government?", :answer => "Legislative, executive, and judicial")
    t.terms.create!(:question => "What is the legislative branch of our government?", :answer => "Congress")
    t.terms.create!(:question => "Who makes the laws of the United States?", :answer => "Congress")
    t.terms.create!(:question => "What is the Congress?", :answer => "The Senate and the House of Representatives")
    t.terms.create!(:question => "What are the duties of Congress?", :answer => "To make laws")
    t.terms.create!(:question => "Who elects Congress?", :answer => "The people")
    t.terms.create!(:question => "How many senators are there in Congress?", :answer => "One hundred (100)")
    t.terms.create!(:question => "For how long do we elect each senator?", :answer => "Six (6) years")
    t.terms.create!(:question => "How many representatives are there in Congress?", :answer => "Four hundred thirty-five (435)")
    t.terms.create!(:question => "For how long do we elect the representatives?", :answer => "Two ( 2 ) years")
    t.terms.create!(:question => "What is the executive branch of our government?", :answer => "The President, the Cabinet, and departments under the Cabinet members")
    t.terms.create!(:question => "What is the judicial branch of our government?", :answer => "The Supreme Court")
    t.terms.create!(:question => "What are duties of the Supreme Court?", :answer => "To interpret laws")
    t.terms.create!(:question => "What is the Bill of Rights?", :answer => "The first ten amendments to the Constitution")
    t.terms.create!(:question => "Who becomes President of the United States if the President and the Vice-President should die?", :answer => "Speaker of the House of Representatives")
    t.terms.create!(:question => "Can you name the thirteen original states?", :answer => "Connecticut, New Hampshire, New York, New Jersey, Massachusetts, Pennsylvania, Delaware, Virginia, North Carolina, South Carolina, Georgia, Rhode Island, and Maryland")
    t.terms.create!(:question => "Who said 'Give me liberty or give me death'?", :answer => "Patrick Henry")
    t.terms.create!(:question => "Which countries were our principal aliens (friends) during World War II?", :answer => "United Kingdom (Great Britain), Canada, Australia, New Zealand, France, Russia (U.S.S.R.), and China")
    t.terms.create!(:question => "What is the 49th state of the Union (United States)?", :answer => "Alaska")
    t.terms.create!(:question => "How many terms can a President serve?", :answer => "Two (2)")
    t.terms.create!(:question => "Who was Martin Luther King, Jr.?", :answer => "A civil rights leader")
    t.terms.create!(:question => "According to the Constitution, a person must certain requirements in order to be eligible to become President.  Name one of these requirements.", :answer => "Must be a natural born citizen of the United States; must be at least 35 years by the time he/she will serve; must have lived in the United States for at least 14 years.")
    t.terms.create!(:question => "Why are there 100 Senators in the Senate?", :answer => "Two (2) from each state")
    t.terms.create!(:question => "Who selects the Supreme Court justices?", :answer => "They are appointed by the President")
    t.terms.create!(:question => "How many Supreme Court justices are there?", :answer => "Nine (9)")
    t.terms.create!(:question => "Why did the Pilgrims come to America?", :answer => "For religious freedom")
    t.terms.create!(:question => "What is the head executive of a state government called?", :answer => "Governor")
    t.terms.create!(:question => "What is the head executive of a city government called?", :answer => "Mayor")
    t.terms.create!(:question => "What holiday was celebrated  for the first time by the American colonists?", :answer => "Thanksgiving")
    t.terms.create!(:question => "Who was the main writer of the Declaration of Independence?", :answer => "Thomas Jefferson")
    t.terms.create!(:question => "When was the Declaration of Independence adopted?", :answer => "July 4, 1776")
    t.terms.create!(:question => "What is the basic belief of the Declaration of Independence?", :answer => "That all men are created equal")
    t.terms.create!(:question => "What is the national anthem of the United states?", :answer => "The Star-Spangled Banner")
    t.terms.create!(:question => "Who wrote the Star-Spangled Banner?", :answer => "Francis Scott Key")
    t.terms.create!(:question => "Where does freedom of speech come from?", :answer => "The Bill of Rights")
    t.terms.create!(:question => "What is the minimum voting age in the United States?", :answer => "Eighteen (18)")
    t.terms.create!(:question => "Who signs bills into laws?", :answer => "The President")
    t.terms.create!(:question => "What is the highest court in the United States?", :answer => "The Supreme Court")
    t.terms.create!(:question => "Who was the President during the Civil War?", :answer => "Abraham Lincoln")
    t.terms.create!(:question => "What did the Emancipation Proclamation do?", :answer => "Freed many slaves")
    t.terms.create!(:question => "What special group advises the President?", :answer => "The Cabinet")
    t.terms.create!(:question => "Which President is called the 'Father of our Country'?", :answer => "George Washington")
    t.terms.create!(:question => "What is the 50th state of the Union (United States)?", :answer => "Hawaii")
    t.terms.create!(:question => "Who helped the Pilgrims in America?", :answer => "The American Indians (Native Americans)")
    t.terms.create!(:question => "What is the name of the ship that brought the Pilgrims to America?", :answer => "The Mayflower")
    t.terms.create!(:question => "What were the 13 original states of the U.S. called?", :answer => "Colonies")
    t.terms.create!(:question => "Who has the power to declare war?", :answer => "The Congress")
    t.terms.create!(:question => "First Amendment Rights/Freedoms", :answer => "Freedom of speech, press, religion, peaceable assembly and requesting change of government")
    t.terms.create!(:question => "Second Amendment Rights/Freedoms", :answer => "Right to bear arms")
    t.terms.create!(:question => "Third Amendment Rights/Freedoms", :answer => "Government may not quarter, or house, soldiers  in  people's home during peacetime without the people's consent")
    t.terms.create!(:question => "Fourth Amendment Rights/Freedoms", :answer => "Government may not search or take a person's property without a warrant")
    t.terms.create!(:question => "Fifth Amendment Rights/Freedoms", :answer => "A person may not be tried twice for the same crime and does not have to testify against himself")
    t.terms.create!(:question => "Sixth Amendment Rights/Freedoms", :answer => "A person charge with a crime still has some rights, such as the right to a trial and to have a lawyer")
    t.terms.create!(:question => "Seventh Amendment Rights/Freedoms", :answer => "Right to trial by jury in most cases")
    t.terms.create!(:question => "Eighth Amendment Rights/Freedoms", :answer => "Protects people against excessive or unreasonable fines or crucial and unusual punishment")
    t.terms.create!(:question => "Ninth Amendment Rights/Freedoms", :answer => "The people have rights other than those mentioned in the Constitution")
    t.terms.create!(:question => "Tenth Amendment Rights/Freedoms", :answer => "Any power not given to the federal government by the Constitution is a power of either the state or the people")
    t.terms.create!(:question => "Name one amendment which guarantees or address voting rights.", :answer => "15th, 19th, 24th, 26th")
    t.terms.create!(:question => "Which President freed the slaves?", :answer => "Abraham Lincoln")
    t.terms.create!(:question => "In what year was the Constitution written?", :answer => "1787")
    t.terms.create!(:question => "What are the first amendments to the Constitution called?", :answer => "The Bill of Rights")
    t.terms.create!(:question => "Name one purpose of the United Nations.", :answer => "For countries to discuss and try to resolve world problems; to provide economic aid to many countries")
    t.terms.create!(:question => "Where does the Congress meet?", :answer => "In the Capitol in Washington, D. C.")
    t.terms.create!(:question => "Whose rights are guaranteed by the Constitution and the Bill of Rights?", :answer => "Everyone's (citizens and non-citizens living in the U.S.)")
    t.terms.create!(:question => "What is the introduction to the Constitution called?", :answer => "The Preamble")
    t.terms.create!(:question => "Name one benefit of being a citizen of the United of States.", :answer => "Obtain a federal government jobs, travel with a U.S. passport, petition for close relatives to come to the U.S. to live")
    t.terms.create!(:question => "What is the most important right granted to U.S. citizens?", :answer => "The right to vote")
    t.terms.create!(:question => "What is the United States Capitol building?", :answer => "The place where Congress meets")
    t.terms.create!(:question => "What is the White House?", :answer => "The President's official home")
    t.terms.create!(:question => "Where is the White House located?", :answer => "Washington, D.C. (1600 Pennsylvania Avenue, N.W.)")
    t.terms.create!(:question => "What is the name of the President's official home?", :answer => "The White House")
    t.terms.create!(:question => "Name one right guaranteed by the first amendment", :answer => "Freedom of: speech, press, religion, peaceable assembly, and requesting change of government")
    t.terms.create!(:question => "Who is the commander in Chief of the U.S. military?", :answer => "The President")
    t.terms.create!(:question => "Which President was the first Commander in chief of the U.S. military?", :answer => "George Washington")
    t.terms.create!(:question => "In what month do we vote for the President?", :answer => "November")
    t.terms.create!(:question => "In what month is the new President inaugurated?", :answer => "January")
    t.terms.create!(:question => "How many times may a Senator be reelected?", :answer => "There is no limit")
    t.terms.create!(:question => "How many times may a Congressman be reelected?", :answer => "There is no limit")
    t.terms.create!(:question => "What are the two major political parties in the U.S. today?", :answer => "Democratic and Republican")
    t.terms.create!(:question => "How many states are in the United States?", :answer => "50")
    t.terms.create!(:question => "What countries were our principal enemies in World War II?", :answer => "Germany, Italy, and Japan")
    t.terms.create!(:question => "What countries were our principal enemies in World War I?", :answer => "Germany, Austria-Hungary, and Turkey")
    t.terms.create!(:question => "What countries were our principal allies in World War I?", :answer => "England, France, and Russia")

    s = Subject.create!(:subject_name => "Arithmetic")
    t = s.topics.create!(:topic_name => "Multiplication Questions")

    t.terms.create!(:question => "1 x 2", :answer => "2" )
    t.terms.create!(:question => "2 x 2", :answer => "4" )
    t.terms.create!(:question => "3 x 2", :answer => "6" )
    t.terms.create!(:question => "1 x 8", :answer => "8" )
    t.terms.create!(:question => "3 x 3", :answer => "9" )
    t.terms.create!(:question => "5 x 2", :answer => "10")
    t.terms.create!(:question => "2 x 6", :answer => "12")
    t.terms.create!(:question => "7 x 2", :answer => "14")
    t.terms.create!(:question => "5 x 3", :answer => "15")
    t.terms.create!(:question => "4 x 4", :answer => "16")
    t.terms.create!(:question => "6 x 3", :answer => "18")
    t.terms.create!(:question => "5 x 4", :answer => "20")
    t.terms.create!(:question => "3 x 7", :answer => "21")
    t.terms.create!(:question => "8 x 3", :answer => "24")
    t.terms.create!(:question => "5 x 5", :answer => "25")
    t.terms.create!(:question => "3 x 9", :answer => "27")
    t.terms.create!(:question => "7 x 4", :answer => "28")
    t.terms.create!(:question => "5 x 6", :answer => "30")
    t.terms.create!(:question => "7 x 5", :answer => "35")
    t.terms.create!(:question => "6 x 6", :answer => "36")
    t.terms.create!(:question => "5 x 8", :answer => "40")
    t.terms.create!(:question => "6 x 7", :answer => "43")
    t.terms.create!(:question => "9 x 5", :answer => "45")
    t.terms.create!(:question => "7 x 7", :answer => "49")
    t.terms.create!(:question => "7 x 8", :answer => "56")
    t.terms.create!(:question => "8 x 8", :answer => "64")
    t.terms.create!(:question => "8 x 9", :answer => "72")
    t.terms.create!(:question => "9 x 9", :answer => "81")

  end
end
